{{- if .Values.authnK8s.configMap.create -}}
# The Golden ConfigMap keeps a reference copy of Conjur configuration information
# that will be used for subsequent operations such as preparing application Namespaces
# for using Conjur Kubernetes authentication.
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ .Values.authnK8s.configMap.name }}
    labels:
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
      app.kubernetes.io/name: "conjur-golden-configmap"
      app.kubernetes.io/component: "conjur-reference-config"
      app.kubernetes.io/instance: "conjur-golden-configmap"
      app.kubernetes.io/part-of: "conjur-config"
      conjur.org/name: "conjur-golden-configmap"
      helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
    # authn-k8s Configuration 
    authnK8sAuthenticatorID: {{ required "A valid authnK8s.authenticatorID is required!" .Values.authnK8s.authenticatorID }}
    authnK8sClusterRole: {{ .Values.authnK8s.clusterRole.name | default "conjur-clusterrole" }}
    authnK8sNamespace: {{ .Release.Namespace }}
    authnK8sServiceAccount: {{ .Values.authnK8s.serviceAccount.name | default "conjur-serviceaccount" }}

    # Conjur Configuration 
    conjurAccount: {{ .Values.conjur.account }}
    conjurApplianceUrl: {{ required "A valid conjur.applianceUrl is required!" .Values.conjur.applianceUrl | trimSuffix "/" }}
    {{- if .Values.conjur.certificateFilePath }}
    {{- if .Values.conjur.certificateBase64 }}
    {{- fail "Only one of 'certificateFilePath' or 'certificateBase64' may be set!" }}
    {{- end }}
    {{- $conjurCert := .Files.Get .Values.conjur.certificateFilePath }}
    {{ if not $conjurCert }}
    {{- fail "If you are using helm install with a (remote) chart reference, please use conjur.certficateBase64 instead of conjur.certificateFilePath. If you are using helm install with a local chart directory, then conjur.certificateFilePath must point to an existing file within the chart directory/subdirectories" }}
    {{- end }}
    conjurSslCertificate: {{ $conjurCert | quote }}
    conjurSslCertificateBase64: {{ $conjurCert | b64enc | quote }}
    {{- else }}
    conjurSslCertificateBase64: {{ required "Either conjur.certificateFilePath or conjur.certificateBase64 are required!" .Values.conjur.certificateBase64 | quote }}
    conjurSslCertificate: {{ .Values.conjur.certificateBase64 | b64dec | quote }}
    {{- end }}
{{- end }}
