apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.authnK8s.serviceAccount.name | default "conjur-serviceaccount" | printf "%.200s" }}-service-account-token
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: "conjur-serviceaccount-token"
    app.kubernetes.io/component: "conjur-kubernetes-identity"
    app.kubernetes.io/instance: "conjur-serviceaccount"
    app.kubernetes.io/part-of: "conjur-config"
    conjur.org/name: "conjur-serviceaccount-token"
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.authnK8s.serviceAccount.name | default "conjur-serviceaccount" }}
type: kubernetes.io/service-account-token
